IDVA5-499-500-correspondence-address-manual-and-confirm
companieshouse/acsp-web pull request #219
Opened 2024-04-02 00:04 UTC by abhiahirv1

Correspondence Address Manual and Confirm Screen

2024-04-02 14:58 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-02 15:16 UTC, ttingle-ch requested changes

2024-04-02 15:16 UTC, ttingle-ch commented on src/test/src/controllers/unicorporatedCorrespondenceAddressConfirmController.test.ts
> +    });
In the test you should check the loaded page is correct using expect(res.text).toContain(Page Heading)

2024-04-02 15:16 UTC, ttingle-ch commented on src/test/src/controllers/unicorporatedCorrespondenceAddressConfirmController.test.ts
> +        const userSession = { firstName: "John", lastName: "Doe", correspondenceAddress: "123 Main St" };
First and last name will not show on unincorporated view

2024-04-02 15:16 UTC, ttingle-ch commented on src/test/src/controllers/unincorporatedCorrespondenceAddressManualController.test.ts
> +            .send({ addressPropertyDetails: "", addressLine1: "pqr", addressLine2: "pqr", addressTown: "lmn", addressCounty: "lmnop", addressCountry: "lmnop", addressPostcode: "MK9 3GB" }).expect(400
add an expect to test the error message shows what is expected for each of the error scenarios

2024-04-02 15:34 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-02 16:31 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-02 16:39 UTC, swalke-ch commented on src/main/controllers/features/unincorporated/unicorporatedCorrespondenceAddressConfirmController.ts
> +import { NextFunction, Request, Response } from "express";
Can you remove  unicorporated from unicorporatedCorrespondenceAddressConfirmController.ts name please? Its already part of  unicorporated feature so no need to add it in name again

2024-04-02 16:40 UTC, swalke-ch commented on src/main/controllers/features/unincorporated/unincorporatedCorrespondenceAddressManualController.ts
> +import { NextFunction, Request, Response } from "express";
same as above

2024-04-03 08:09 UTC, ttingle-ch commented on src/test/src/controllers/unincorporatedCorrespondenceAddressManualController.test.ts
> +// Test for no addressCountry, will return 302.
Country is a mandatory field so should return 400 if no country is provided

2024-04-03 08:09 UTC, ttingle-ch commented on src/test/src/controllers/unincorporatedCorrespondenceAddressManualController.test.ts
> +    });
Missing expected text

2024-04-03 09:23 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-03 09:28 UTC, ttingle-ch approved these changes

2024-04-03 09:33 UTC, swalke-ch approved these changes

2024-04-03 09:35 UTC, merged